### ISSUE TITLE
Properly break long HTML lines / breaklines and breakanywhere directives

### ISSUE THREAD

**Issue by Noki** [gpoore/fvextra#11]
If you have very long words in an markdown codeblock and try to convert it to an PDF using pandoc, the breaklines and breakanywhere directives do not work as expected.

I tried to report this issue in the pandoc issue tracker before (https://github.com/jgm/pandoc/issues/6069). It was pointed out that it is an fvextra issue.

Input:

[pandoc-test.txt](https://github.com/gpoore/fvextra/files/4066213/pandoc-test.txt)

Output:

![image](https://user-images.githubusercontent.com/198902/72454372-06c4d480-37c1-11ea-83ea-4d564f77196d.png)

Expected Output:

The long URL should be broken in between, and have an indicator showing that it's the same line. The line break should respect the page margin.

Pandoc Version:

pandoc 2.9.1.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: C:\Users\Tobias Schwarz\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web: https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

Steps to reproduce:

Use the attached [pandoc-test.txt](https://github.com/gpoore/fvextra/files/4066213/pandoc-test.txt) with the following commandline:

pandoc -f markdown -o pandoc-test.pdf pandoc-test.txt

Best regards
Tobias

**Comment by muzimuzhi** [comment]
There are two sub-problems to solve:
1. `breakanywhere` skips `{...}` by default, and users should use `\FancyVerbBreakStart` and `\FancyVerbBreakStop` inside the markup command (here is `\StringTok`) to allow auto break inside `{...}`. See documentation of `fvextra`, sec. 7.3.1 & 7.3.2.
2. Currently `\textcolor` is used inside `\StringTok`, and the former command can produce one-line output only.

Here is a latex-side workaround, using the simplified form of example from https://github.com/jgm/pandoc/issues/6069#issuecomment-574751948:
```tex
\documentclass{article}
\usepackage{xcolor}
\usepackage{fvextra}

\newenvironment{Shaded}{}{}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}
  {breaklines,breakanywhere,commandchars=\\\{\}}

\makeatletter
\newcommand{\@StringTok}[1]{#1}
\newcommand{\StringTok}[1]{%
  \color[rgb]{0.25,0.44,0.63}\expandafter\FancyVerbBreakStart\@StringTok{#1}\FancyVerbBreakStop\normalcolor}
\makeatother

\begin{document}

\begin{Shaded}
\begin{Highlighting}[]
"https://www.example.com/dgjlb4r7cu0elacgpbdgjlb4r7cu0elacgpb/nwl4858soq59jkq5ijl5sdgjlb4r7cu0elacgpbv56uegqp500gijn7vo1s1jcsnn86an7.jpg"

\StringTok{"https://www.example.com/dgjlb4r7cu0elacgpbdgjlb4r7cu0elacgpb/nwl4858soq59jkq5ijl5sdgjlb4r7cu0elacgpbv56uegqp500gijn7vo1s1jcsnn86an7.jpg"}
\end{Highlighting}
\end{Shaded}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/72468065-43231f80-3817-11ea-8fec-05dfc9d09434.png)

If I am right, an overall solution needs some change to python library [`Pygments`](https://pygments.org/), which is used by latex package `minted` to analysis and highlight the contents of environment `Highlighting`.

**Comment by muzimuzhi** [comment]
> If I am right, an overall solution needs some change to python library Pygments, which is used by latex package minted to analysis and highlight the contents of environment Highlighting.

I am wrong. With `pandoc -s -f markdown -o pandoc-test.tex pandoc-test.txt`, the output `pandoc-test.tex` file shows that it is `pandoc` that analysis and highlight the contents of code block in markdown. So, it is `pandoc` that should change the way `\StringTok` (and similar markup commands) are defined.

**Comment by gpoore** [comment]
Line breaking works in purely verbatim text. Once `commandchars` are involved, things become more complicated. Breaks are not inserted within macro arguments because it isn't possible in general to determine whether a mandatory macro argument represents text that is inserted (and thus needs breaks) or something else. Macros can work around this by wrapping inserted text with `\FancyVerbBreakStart` and `\FancyVerbBreakStop`. This is how `minted` and `pythontex` manage line breaking for highlighted code.

One option for working around this is to redefine pandoc's highlighting macros. Here's a version of the example document that does this: [pandoc-test.txt](https://github.com/gpoore/fvextra/files/4067378/pandoc-test.txt).

In a future version of `fvextra`, I could add a `pandoc` option for patching the highlighting macros. It may not be possible to patch them automatically without using a special option...I'm not sure that there is a good way to determine whether a LaTeX document has been generated by pandoc. Since pandoc doesn't use `fvextra` by default, it probably doesn't make sense to redefine the highlighting macros on the pandoc side.

**Comment by gpoore** [comment]
The development version on GitHub has a new feature `breaknonspaceingroup` that automatically makes Pandoc's highlighted code output compatible with all line-breaking options. I've updated the documentation with an example of how to use this with Pandoc Markdown. A new `fvextra` release including this feature will be on CTAN within the next few days.
